
# Terraform Action to lint and apply updated redirects
name: Promote Staging Content and Redirects to Production
on:
  pull_request:
    branches:
      - master
jobs:
  publish-to-prod:
    if: github.head_ref == 'stage'
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/redirect_creation
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: create Terraform Tfvars
        id: tfvars
        run: |
          cat << EOF > terraform.auto.tfvars 
            stage                 = "prod"
          EOF

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      - uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_AWS_KEY }}
          aws-region: us-east-1

      - name: Promote Staging Content to Production
        run:
          aws s3 sync s3://stage-docsstageliquibasecom-origin/ s3://prod-docsliquibasecom-origin/ --recursive --delete --exclude "robots.txt"

