# Terraform Action to lint and apply updated redirects
name: Publish Staging Redirects
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  publish-staging-redirects:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: scripts/redirect_creation
    steps:
      - name: Checkout branch with draft redirects
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: create Terraform Tfvars
        id: tfvars
        run: |
          cat << EOF > terraform.auto.tfvars
            stage                 = "staging"
            docs_access_key       = ${{ secrets.DOCS_AWS_KEY_ID }}
            docs_secret_key       = ${{ secrets.DOCS_AWS_KEY }}
          EOF

      - name: Terraform Format
        if: ${{ github.event_name == 'pull_request' }}
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        if: ${{ github.event_name == 'pull_request' }}
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: ${{ github.event_name == 'pull_request' }}
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      - uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

      - name: Terraform Apply
        if: ${{ github.event_name == 'push' }}
        run: terraform apply -auto-approve
